apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy-$(deploymentName)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiservice-$(deploymentName)
  template:
    metadata:
      labels:
        app: apiservice-$(deploymentName)
    spec:
      containers:
      - name: apiservice-$(deploymentName)
        image: vcr.vngcloud.vn/106160-docker-images/apiservice:latest
        resources:
          requests:
            cpu: "300m"
            memory: "400Mi"
          limits:
            cpu: "600m"
            memory: "800Mi"
        volumeMounts:
        - name: google-credentials
          mountPath: /var/secrets/google
        - name: mssql-secret
          mountPath: /var/secrets/mssql
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/asoft-erp-firebase-adminsdk-7vzks-f1d0261521.json
        - name: DbConnectionStrings__ConnectionStrings__Business
          value: Server=$(SQLSERVER),1433;initial catalog=1BOSS_$(deploymentName);user id=sa;password=$(SA_PASSWORD);Encrypt=false;TrustServerCertificate=True;Connection Timeout=30;
        - name: DbConnectionStrings__ConnectionStrings__Admin
          value: Server=$(SQLSERVER),1433;initial catalog=AS_ADMIN_1BOSS_$(deploymentName);user id=sa;password=$(SA_PASSWORD);Encrypt=false;TrustServerCertificate=True;Connection Timeout=30;
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: google-credentials
        secret:
          secretName: google-credentials
      - name: mssql-secret
        secret:
          secretName: mssql
---
apiVersion: v1
kind: Service
metadata:
  name: api-clusterip-srv-$(deploymentName)
spec:
  type: ClusterIP
  selector:
    app: apiservice-$(deploymentName)
  ports:
  - name: apiservice-$(deploymentName)
    protocol: TCP
    port: 80
    targetPort: 80
