apiVersion: batch/v1
kind: Job
metadata:
  name: restore-databases-job-$(deploymentName)
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: sqlcmd
        image: mcr.microsoft.com/mssql-tools
        command:
        - /bin/bash
        - -c
        - |
          dbPassword=$(cat /mnt/secrets/SA_PASSWORD)
          serverName=$(SQLSERVER)

          /opt/mssql-tools/bin/sqlcmd -S $serverName -U sa -P $dbPassword -Q "
            USE [master]
            RESTORE DATABASE [1BOSS_$(dbName)]
            FROM DISK = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\1BOSS.bak'
            WITH
                MOVE N'ASOFT' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\1BOSS_$(dbName).mdf',
                MOVE N'ASOFT_log' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\1BOSS_$(dbName).ldf',
                NOUNLOAD, REPLACE;

            USE [master]
            RESTORE DATABASE [AS_ADMIN_1BOSS_$(dbName)]
            FROM DISK = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Backup\AS_ADMIN_1BOSS.bak'
            WITH
                MOVE N'AS_ADMIN_ASOFT' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AS_ADMIN_1BOSS_$(dbName).mdf',
                MOVE N'AS_ADMIN_ASOFT_log' TO N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AS_ADMIN_1BOSS_$(dbName).ldf',
                NOUNLOAD, REPLACE;
          "
        volumeMounts:
          - name: secrets-volume
            mountPath: /mnt/secrets
      restartPolicy: OnFailure
      volumes:
        - name: secrets-volume
          secret:
            secretName: mssql
  backoffLimit: 4
